apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-spot-operator-pg1
  labels:
    app: pg-spot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-spot-operator
      pgso-instance-name: pg1
  template:
    metadata:
      labels:
        app: pg-spot-operator
        pgso-instance-name: pg1
    spec:
      containers:
      - name: pg-spot-operator
        image: pgspotops/pg-spot-operator:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        env:
          # All ENV options described here:
          # https://github.com/pg-spot-ops/pg-spot-operator/blob/main/docs/README_env_options.md
          - name: INSTANCE_NAME
            value: pg1
          - name: REGION
            value: "eu-north-1"
          - name: STORAGE_MIN
            value: "50"
          - name: STORAGE_TYPE
            value: "local"
          - name: CPU_MIN
            value: "1"
          - name: POSTGRES_VERSION
            value: "16"
          - name: AWS_ACCESS_KEY_ID
            value: "aaaa"
          - name: AWS_SECRET_ACCESS_KEY
            value: "bbbb"
          - name: ADMIN_USER
            value: "mypostgres"
          - name: ADMIN_PASSWORD
            value: "mypostgressecret"
          - name: PRIVATE_IP_ONLY
            value: "false"
          - name: SSH_KEYS
            value: "ssh-rsa ..."
