---
- name: Enable unattended security upgrades using role default settings
  ansible.builtin.include_role:
    name: debops.debops.unattended_upgrades
  vars:
    unattended_upgrades__enabled: os.unattended_security_upgrades|d(True)
    unattended_upgrades__auto_reboot: True

- block:

  - name: Setting kernel parameters - vm.overcommit_memory
    ansible.posix.sysctl:
      name: vm.overcommit_memory
      value: '2'
    ignore_errors: true

  - name: Setting kernel parameters - vm.overcommit_ratio
    ansible.posix.sysctl:
      name: vm.overcommit_ratio
      value: '100'
    ignore_errors: true

  - name: Setting kernel parameters - vm.swappiness
    ansible.posix.sysctl:
      name: vm.swappiness
      value: '1'
    ignore_errors: true

  when: os.kernel_tuning|d(True)

# Disable Transparent Huge Pages, generally considered bad for databases that manage their own memory
- name: Set up a SystemD unit
  ansible.builtin.template:
    src: disable-thp.service.j2
    dest: /etc/systemd/system/disable-thp.service

- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Ensure service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: disable-thp
