---
- name: Set up pg_hba.conf
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgres.version|d(16) }}/{{ postgres_cluster_name }}/pg_hba.conf"
    line: "{{ item }}"
  loop: "{{ postgres.pg_hba_lines | d([]) or def_pg_hba_lines }}"
  register: changed

- name: Reload Postgres config
  ansible.builtin.service: "name=postgresql@{{ postgres.version|d(16) }}-{{ postgres_cluster_name }} state=reloaded"
  when: changed
  changed_when: false
