---
- name: Set authorized key from literal string
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    path: ~/.ssh/authorized_keys2
    key: "{{ item }}"
  loop: "{{ access.extra_ssh_pub_keys | d([]) }}"

- name: Set authorized key from file
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    path: ~/.ssh/authorized_keys2
    key: "{{ lookup('file', item) }}"
  loop: "{{ access.extra_ssh_pub_key_paths | d([]) }}"
