---
- file:
    path: input
    state: directory

- file:
    path: input/{{ section_name }}
    state: directory

- name: Dump normal keys - {{ section_name }}
  copy:
    content="{{ plain_items.value }}" dest=./input/{{ section_name }}/{{ plain_items.key }}
  when:
    - plain_items.value | d("") | type_debug not in ["list", "dict"]
  loop: "{{ section_data | d({}) | dict2items }}"
  loop_control:
    loop_var: plain_items

- name: Lists - {{ section_name }}
  include_tasks: dump_list.yml
  vars:
    dump_root: "{{ lookup('ansible.builtin.pipe', 'pwd') }}/input/{{ section_name }}"
    list_key: "{{ lists_items.key }}"
    list_values: "{{ lists_items.value }}"
  when:
    - lists_items.value | type_debug == "list"
  loop: "{{ section_data | d({}) | dict2items }}"
  loop_control:
    loop_var: lists_items

- name: Top level dicts
  include_tasks: dump_dict.yml
  vars:
    dump_root: "{{ lookup('ansible.builtin.pipe', 'pwd') }}/input/{{ section_name }}"
    dict_to_dump_key: "{{ dict_items.key }}"
    dict_to_dump: "{{ dict_items.value }}"
  when:
    - dict_items.value | type_debug == "dict"
  loop: "{{ section_data | d({}) | dict2items }}"
  loop_control:
    loop_var: dict_items
