---
# Available in manifests
instance_name: spot
pg:
  major_ver: 16
access:
  pg_hba:
    - "host all postgres 0.0.0.0/0 reject"
    - "hostssl all all 0.0.0.0/0 scram-sha-256"

postgres_cluster_name: "{{ instance_name | replace('-', '_') }}"  # Dashes don't work with pg_createcluster
